### ISSUE TITLE
Automated build script

### ISSUE THREAD

**Issue by dbernar1** [yagudaev/winnipegjs#23]
Hey,

I'd like to add a build script, alike the tests, as a way to show an example build script, and to get input from you on getting better at creating those as well.

The script would need to do something, but there isn't much it has to do yet...so we would need ideas for what the script would do before we can make one. I was thinking maybe it could compile front end coffee-script, or pre-process a CSS language like SASS, or run the tests if we have any.

Let me know what you think. Thanks.

**Comment by yagudaev** [comment]
Checkout [Middleman](http://middlemanapp.com/) for some inspiration on what a static site can do. Middleman has a command to build resources similar to Rails.

So you can mimic their process. Put the build resources into a `build` directory or use the Rails approach of putting things into `public/assets`. I do like the `assets` folder in Rails with automatic invocation of the right interpreter based on the extension. I am sure someone already built that however. I know that `harp.io` guys have `https://github.com/sintaxi/terraform` and their entire platform is open source so you can view it here: https://github.com/sintaxi/harp.

Another thing is to invoke the build script automatically as part of the deploy process. Otherwise it becomes really annoying. When we worked with @pbraun on our SnippetSky and we had a RequireJS build script, I can't remember the number of times I forgot to build it before deploying. We also needed to have the build code as part of the source code on git (eww I know). So in heroku as part of the Ruby build-pack we can use the `rake assets:precompile` to run the build script before the slug gets pushed to heroku. There should be something similar for node, or we will have to create a custom-build pack.

You can also just use a separate repo if all you want to do is have an example of how to build a build script for node.

So for my own experience, it is not worth doing a build script for something this small unless:
1. Scripts get compiled on demand (so you don't have to keep building them in development). This can be achieved by doing a watch on the directory or better yet lazy evaluation by intercepting requests for assets and compiling them if they don't exist. Rails does the latter and compiles assets on the fly, caching them in the tmp/ directory of the project.
2. Assets are build automatically when deploying
3. Assets get the right interpreter/compiler based on the file extension

**Comment by dbernar1** [comment]
Interesting angle. I was thinking gulp/grunt, but now I get to learn about these too. I will get back to you after I get a chance to look into it.

**Comment by yagudaev** [comment]
Yep that is the right direction :). Gulp and grunt are good. Just some inspiration from a well established language/framework.

**Comment by dbernar1** [comment]
Ah, so it is the same approach. Gotcha now - didn't read it properly first time.
